import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import client from '../api/client.js';

const CARD = 'rounded-lg border border-slate-200 bg-white p-6 shadow-sm';
const PRIMARY_BUTTON =
  'rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed';
const ERROR_BANNER = 'rounded-md bg-red-50 border border-red-200 text-red-700 px-4 py-3 text-sm';
const SUCCESS_BANNER = 'rounded-md bg-emerald-50 border border-emerald-200 text-emerald-700 px-4 py-3 text-sm';

function maskToken(token) {
  if (token.length <= 8) return token;
  return `${token.slice(0, 4)}…${token.slice(-4)}`;
}

export default function DiscordLink() {
  const [searchParams] = useSearchParams();
  const token = searchParams.get('token');

  const [submitting, setSubmitting] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);

  async function confirmLink() {
    setSubmitting(true);
    setError(null);
    try {
      // Identity comes from the Authorization header client.js already attaches — the backend
      // resolves the acting user from the session, not from anything sent in this body.
      const res = await client.post('/api/auth/discord/link/complete', { token });
      setResult(res.data.message || 'Discord account linked.');
    } catch (err) {
      setError(err.response?.data?.error || 'Failed to link Discord account.');
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div className="space-y-8">
      <h1 className="text-2xl font-semibold text-slate-900">Link Discord account</h1>

      <div className={CARD}>
        {!token ? (
          <p className="text-sm text-slate-500">
            This page expects a link generated by the <span className="font-mono">/link</span> command
            in the Discord bot. Run that command in Discord and open the URL it gives you.
          </p>
        ) : result ? (
          <>
            <div className={SUCCESS_BANNER}>{result}</div>
            <Link to="/profile" className="mt-4 inline-block text-sm font-medium text-blue-600 hover:text-blue-700">
              Back to profile
            </Link>
          </>
        ) : (
          <>
            <p className="text-sm text-slate-500">
              Link token: <span className="font-mono text-slate-900">{maskToken(token)}</span>
            </p>
            <p className="mt-1 text-sm text-slate-500">
              Confirm below to connect this trading account to your Discord account.
            </p>

            {error && <div className={`mt-4 ${ERROR_BANNER}`}>{error}</div>}

            <button
              type="button"
              onClick={confirmLink}
              disabled={submitting}
              className={`mt-4 ${PRIMARY_BUTTON}`}
            >
              {submitting ? 'Linking…' : 'Confirm link'}
            </button>
          </>
        )}
      </div>
    </div>
  );
}
